### ISSUE TITLE
Question about `core_pipe_limit`

### ISSUE THREAD

**Issue by gotzl** [diamon/minicoredumper#4]
In the `core_pipe_limit` section of https://man7.org/linux/man-pages/man5/core.5.html it reads 

> ... A value of 0 in this file is special ... no waiting will take place (i.e., the collecting program is not guaranteed access to /proc/<crashing-PID>) ... The default value for this file is 0.

Am I correct that when using minicoredumper, one should set `core_pipe_limit > 0` since it heavily uses `/proc/<crashing-PID>`? I did not find s.t. about this setting in minicoredumper docs ...

Reason I ask is because for me, minicoredumper sometimes enters an infinite loop in which it hangs in `read_remote` ("No such file or directory"). Now I saw the latest two commits which should also help, but I believe the fundamental issue in my case could be that `/proc/<crashing-PID>` disappears ...

**Comment by jogness** [comment]
I did not know about this, but looking at the kernel source, it is definitely a problem for minicoredumper users! Thank you for pointing this out!

I am wondering how best to handle this. Should the minicoredumper print a warning somewhere if it is 0? Perhaps the minicoredumper start scripts should return an error if it is 0? I do not think the minicoredumper should automatically set some non-zero value. This should be set in sysctl.conf by the admin.

The inifinite read_remote() loop that was fixed in git is due to ELF parsing of the process memory space. But it looks like that too is cleaned up without waiting for the userspace dumper. I will need to do some more tests on this, but regardless:

**kernel.core_pipe_limit needs to be non-zero**

John Ogness

**Comment by gotzl** [comment]
Thanks for the quick response and confirmation of the possible problem!

I had a very brief look into the kernel code myself and I'm puzzled why this issue seems to be so rare ... Also, I'm still struggling to really reproduce/trigger it with my setup ... 

> I do not think the minicoredumper should automatically set some non-zero value. This should be set in sysctl.conf by the admin.

I totally agree. I'm too not sure what the best behavior for minicoredumper would be, though. But at least one could catch the `ENOENT` and give a sensible error message, I guess.

**Comment by jogness** [comment]
I did some further investigation. It turns out that the default value (0) is sufficient for the minicoredumper to work correctly. The userspace core dumping application receives the core file per stdin. Even if kernel.core_pipe_limit is set to 0, the kernel waits until the userspace core dumping application has finished reading the core file. For the minicoredumper, the core file is read at the very end or processing. So /proc information is no longer needed anyway.

Despite this, I have added code in the init script for the recently released 2.0.2 version that puts the max value into kernel.core_pipe_limit (0x7fffffff) on start.

BTW: The problem you also mentioned is about the infinite loop is also solved with the 2.0.2 release.
